### ISSUE TITLE
write direct messages to a User in a room

### ISSUE THREAD

**Issue by SlowMoschen** [SlowMoschen/Chat.IO#1]
Add 3 dots button to message bubbles
menu selection with "direct Message to 'User XY' "
send Message to User
Slight variation in the message bubbles for direct messages

**Comment by SlowMoschen** [comment]
Added Feature

**Comment by anannyyaak-teemmpp** [comment]
hey which api are you using in thelibrary management system

**Comment by anannyyaak-teemmpp** [comment]
![image](https://github.com/SlowMoschen/Chat.IO/assets/102593010/a84d2aa0-ac64-477d-80e3-705a9225b561)
in this part

**Comment by anannyyaak-teemmpp** [comment]
![image](https://github.com/SlowMoschen/Chat.IO/assets/102593010/c1e8e27c-3b3f-4e78-a915-41ec031c35cd)
also this error

**Comment by SlowMoschen** [comment]
Hey!

I am using my own API Url, where i hosted the NodeJS Application. So if you are runnig the App on your own PC, just enter the localhost URL with your chosen port and the right endpoint.
